name: linter

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Prepare Laravel CI environment
        uses: ./.github/actions/laravel-ci-prepare
        timeout-minutes: 5
        env:
          COMPOSER_AUTH: >-
            {"http-basic":{"composer.fluxui.dev":{"username":"${{ secrets.FLUX_USERNAME }}","password":"${{ secrets.FLUX_LICENSE_KEY }}"}}}
        with:
          bootstrap-laravel: "false"
          create-sqlite-database: "false"
          composer-install-command: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Pint
        run: vendor/bin/pint

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          commit_message: fix code style
          commit_options: "--no-verify"
          file_pattern: |
            **/*
            !.github/workflows/*
